// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR435kzkDozONN_KksACkyUvfkRVxRu8Q',
    appId: '1:451492499108:web:769f94bb23fb6f6cba2031',
    messagingSenderId: '451492499108',
    projectId: 'recipeapp-d82c1',
    authDomain: 'recipeapp-d82c1.firebaseapp.com',
    storageBucket: 'recipeapp-d82c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWXy6kV5aKJYopVfbpCPlyTsw-JvKfzuM',
    appId: '1:451492499108:android:67aee5e101c96f89ba2031',
    messagingSenderId: '451492499108',
    projectId: 'recipeapp-d82c1',
    storageBucket: 'recipeapp-d82c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_HyIX7vTSgK1t8Jcj7lTio-YWq_mDqdc',
    appId: '1:451492499108:ios:907971eb6ae85203ba2031',
    messagingSenderId: '451492499108',
    projectId: 'recipeapp-d82c1',
    storageBucket: 'recipeapp-d82c1.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );
}
